# Generated by Django 4.0.6 on 2022-09-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_skill2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentice',
            name='idApprenticeFK',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userApprentice', to='api.user'),
        ),
    ]
